### ISSUE TITLE
Build is incorrectly reporting success

### ISSUE THREAD

**Issue by dblock** [matt-kruse/alexa-app#107]
```
Unhandled rejection AssertionError: expected 'INITIAL TEST VALUE WHICH SHOULD BE OVERRIDDEN' to equal undefined
    at assertEqual (/home/travis/build/matt-kruse/alexa-app/node_modules/chai/lib/chai/core/assertions.js:487:12)
    at ctx.(anonymous function) (/home/travis/build/matt-kruse/alexa-app/node_modules/chai/lib/chai/utils/addMethod.js:41:25)
    at doAsserterAsyncAndAddThen (/home/travis/build/matt-kruse/alexa-app/node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
    at null.<anonymous> (/home/travis/build/matt-kruse/alexa-app/node_modules/chai-as-promised/lib/chai-as-promised.js:255:21)
    at ctx.(anonymous function) [as equal] (/home/travis/build/matt-kruse/alexa-app/node_modules/chai/lib/chai/utils/overwriteMethod.js:49:33)
    at /home/travis/build/matt-kruse/alexa-app/test/test_alexa_app_session.js:229:55
    at tryCatcher (/home/travis/build/matt-kruse/alexa-app/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/matt-kruse/alexa-app/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/travis/build/matt-kruse/alexa-app/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromiseAtPostResolution (/home/travis/build/matt-kruse/alexa-app/node_modules/bluebird/js/main/promise.js:248:10)
    at Async._drainQueue (/home/travis/build/matt-kruse/alexa-app/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/travis/build/matt-kruse/alexa-app/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/travis/build/matt-kruse/alexa-app/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

https://travis-ci.org/matt-kruse/alexa-app/builds/187971131

**Comment by dblock** [comment]
@trayburn I think these are yours

**Comment by trayburn** [comment]
I agree, these are mine.  Out of curiosity do these reproduce for you locally?  I do not get them running mocha on my box (obviously or I wouldn't have put this up for PR to begin with).  I'm trying to decide if this is a build script issue, or my box issue and then a general code issue.

**Comment by trayburn** [comment]
Correction, these do repro on my box, but they ALSO don't fail the build there.  Working on this now, will get a PR for this sometime in the next 6 hours or so.

**Comment by dblock** [comment]
I am seeing the same as in CI, ie. the output error, but not failing the `npm test` run. I've been trying to fix the latter without any luck.

**Comment by dblock** [comment]
I think this is fundamentally incorrect:

```js
          return app.request(mockRequest)
            .then(() => returnedAttributeValue.should.equal(undefined))
            .should.eventually.succeed;
```

shouldn't it just return the promise?

```
          return app.request(mockRequest)
            .then(() => returnedAttributeValue.should.equal(undefined))
```

**Comment by dblock** [comment]
See https://github.com/matt-kruse/alexa-app/pull/109, @trayburn there's at least a logical change there, take a look?
